global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nodes"

    static_configs:
      - targets: ["<master-node-ip>:9100","<slave-node-1-ip>:9100","<slave-node-2-ip>:9100","<slave-node-3-ip>:9100"]